kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: centos-learning
spec:
  selector:
    matchLabels:
      os: centos
  replicas: 1
  template:
    metadata:
      labels:
        os: centos
    spec:
      containers:
      - name: centos
        image: centos:7
        ports:
        - containerPort: 80
